#' @title Count Leaves in a Decision Tree
#' @description
#' Recursively counts the number of leaf nodes in a (sub)tree.
#' Used internally for cost–complexity pruning and tree statistics.
#' @param node A tree node object (leaf or internal) generated by \code{generate_tree}.
#' @return Integer, number of leaf nodes in the subtree.
#' @keywords internal
count_leaves <- function(node) {
  if (is.null(node$split_feature)) {
    return(1)
  }
  count_leaves(node$left) + count_leaves(node$right)
}

#' @title Subtree Misclassification Error
#' @description
#' Computes the weighted misclassification error of a subtree.
#' Used internally for cost–complexity pruning in \code{generate_tree}.
#' @param node A tree node object (leaf or internal) generated by \code{generate_tree}.
#' @return Numeric value of the weighted misclassification error (0–1).
#' @details
#' - For leaf nodes, returns 1 minus the maximum class probability at the node.
#' - For internal nodes, computes the weighted average of left and right subtree errors
#'   based on the number of samples at each child node.
#' @keywords internal
subtree_error <- function(node) {
  if (is.null(node$split_feature)) {
    return(1 - max(node$probs))
  }
  ln <- node$left$n
  rn <- node$right$n
  le <- subtree_error(node$left)
  re <- subtree_error(node$right)
  (ln * le + rn * re) / (ln + rn)
}
